[project]
name = "streamclick"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "little-fox28", email = "tranthjnh288@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.34.0",
    "boto3-stubs~=1.43.102",
    "confluent-kafka>=2.8.2,<2.12.0",
    "duckdb>=1.0.0",
    "fastapi>=0.111.0",
    "kagglehub>=1.0.2",
    "pandas>=2.0.0",
    "psycopg2-binary>=2.9.9",
    "pyarrow>=16.1.0",
    "pydantic>=2.7.0,<2.11.0",
    "pydantic-settings>=2.3.0,<2.12.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.0.1",
    "quixstreams>=3.0.0",
    "requests>=2.34.2",
    "urllib3>=2.8.0",
    "uvicorn[standard]>=0.30.0",
]

[project.scripts]
streamclick = "streamclick:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx2>=2.13.1",
    "kafka-python>=3.0.11",
    "requests>=2.34.2",
]

[tool.pyright]
extraPaths = ["."]

