[pytest]
pythonpath = .
markers =
    unit: Tests that do not require external services (Mocking 100%).
    integration: Tests connecting multiple components but still isolated from real external infrastructure.
    e2e: Full system tests requiring a running environment (Docker/MinIO/Kafka).
testpaths = tests
